version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mysqldatabase
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    container_name: mysql-db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
