# MySql version 5.x
#   gem install mysql2
#
#   Ensure the Mysql 2 gem is defined in your Gemfile
#   gem 'mysql2'
#
development:
  adapter: mysql2
  encoding: utf8
  database: contact_development
  username: <%= ENV['MYSQL_DOCKER_USER'] %>
  password: <%= ENV['MYSQL_DOCKER_PWD'] %>
  host: <%= ENV['MYSQL_DOCKER_HOST'] %>
  port: <%= ENV['MYSQL_DOCKER_PORT'] %>


test:
  adapter: mysql2
  encoding: utf8
  database: contact_test
  username: <%= ENV['MYSQL_DOCKER_USER'] %>
  password: <%= ENV['MYSQL_DOCKER_PWD'] %>
  host: <%= ENV['MYSQL_DOCKER_HOST'] %>
  port: <%= ENV['MYSQL_DOCKER_PORT'] %>


